alias -- console='javaws -J-Djava.security.properties=/home/cpayne/.config/icedtea-web/disabled_tls.properties'
alias -- gs='git status'
alias -- l='ls -alh'
alias -- ll='ls -l'
alias -- ls='ls --color=tty'
alias -- m='ssh cpayne.nine.ch'
alias -- mo='mosh --no-init cpayne.nine.ch'
alias -- myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias -- autoremove='sudo pacman -Rns'
alias -- clr-cache='sudo pacman -Scc'
alias -- install='sudo pacman -S'
alias -- local-install='sudo pacman -U'
alias -- pkg-info='sudo pacman -Qi'
alias -- remove='sudo pacman -R'
alias -- search='sudo pacman -Ss'
alias -- search-local='sudo pacman -Qs'
alias -- sync='sudo pacman -Syyy'
alias -- unlock='sudo rm /var/lib/pacman/db.lck'
alias -- update='sudo pacman -Syyu'

